services:
  algasensors-rabbitmq:
    image: rabbitmq:3-management
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - algasensors-rabbitmq:/var/lib/rabbitmq/
      - ./.config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - algasensors-network

  algasensors-processor:
    build:
      context: ./processor
    env_file:
      - ./processor/.env
    restart: no
    ports:
      - "8082:8082"
    volumes:
      - ./processor/logs:/app/src/main/resources/logs
    depends_on:
      algasensors-rabbitmq:
        condition: service_healthy
    networks:
      - algasensors-network


  algasensors-monitor:
    build:
      context: ./monitor
    env_file:
      - ./monitor/.env
    restart: no
    ports:
      - "8081:8081"
    volumes:
      - monitor-data:/app/data
      - ./monitor/logs:/app/src/main/resources/logs
    depends_on:
      algasensors-processor:
        condition: service_started
      algasensors-rabbitmq:
        condition: service_healthy
    networks:
      - algasensors-network

  algasensors-manager:
    build:
      context: ./manager
    env_file:
      - ./manager/.env
    restart: no
    ports:
      - "8080:8080"
    volumes:
      - manager-data:/app/data
      - ./manager/logs:/app/src/main/resources/logs
      - ./manager/src/main/resources/database:/app/src/main/resources/database
    depends_on:
      algasensors-monitor:
        condition: service_started
      algasensors-rabbitmq:
        condition: service_healthy
    networks:
      - algasensors-network  

  algasensors-seeder:
    build:
      context: ./seeder
    env_file:
      - ./seeder/.env
    restart: no
    ports:
      - "8083:8083"
    volumes:
      - ./seeder/logs:/app/src/main/resources/logs
    depends_on:
      algasensors-manager:
        condition: service_started
      algasensors-processor:
        condition: service_started
    networks:
      - algasensors-network

  algasensors-client:
    build:
      context: ./client
    restart: no
    ports:
      - "80:80"
    networks:
      - algasensors-network

volumes:
  algasensors-rabbitmq:
  manager-data:
  monitor-data:

networks:
  algasensors-network:
