services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - ./.config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - algasensors-network

  processor:
    build:
      context: ./processor
    env_file:
      - ./processor/.env
    restart: no
    ports:
      - "8082:8082"
    volumes:
      - ./processor/logs:/app/src/main/resources/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - algasensors-network


  monitor:
    build:
      context: ./monitor
    env_file:
      - ./monitor/.env
    restart: no
    ports:
      - "8081:8081"
    volumes:
      - monitor-data:/app/data
      - ./monitor/logs:/app/src/main/resources/logs
    depends_on:
      processor:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - algasensors-network

  manager:
    build:
      context: ./manager
    env_file:
      - ./manager/.env
    restart: no
    ports:
      - "8080:8080"
    volumes:
      - manager-data:/app/data
      - ./manager/logs:/app/src/main/resources/logs
      - ./manager/src/main/resources/database:/app/src/main/resources/database
    depends_on:
      monitor:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - algasensors-network

  generator:
    build:
      context: ./generator
    env_file:
      - ./generator/.env
    restart: no
    ports:
      - "8083:8083"
    volumes:
      - ./generator/logs:/app/src/main/resources/logs
    depends_on:
      manager:
        condition: service_started
      processor:
        condition: service_started
    networks:
      - algasensors-network

  # client:
  #   build:
  #     context: ./client
  #   restart: no
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     manager:
  #       condition: service_started
  #   networks:
  #     - algasensors-network

volumes:
  rabbitmq-data:
  manager-data:
  monitor-data:

networks:
  algasensors-network:
